# Define variables for colors and styles
vars: {
  math-fill: "#FFF2CC"
  math-stroke: "#916f0c"
  cs-fill: "#d6ddff"
  cs-stroke: "#0D32B2"
  cs-stroke-elective: "black"
  cs-fill-elective: "#f7f7f7"
  dash-style: 3
}

20474: {
  label: "אינפי 1"
  style: {
    fill: ${math-fill}
    stroke: ${math-stroke}
  }
}

20475: {
  label: "אינפי 2"
  style: {
    fill: ${math-fill}
    stroke: ${math-stroke}
  }
}

20476: {
  label: "מתמטיקה בדידה"
  style: {
    fill: ${math-fill}
    stroke: ${math-stroke}
  }
}

20109: {
  label: "לינארית 1"
  style: {
    fill: ${math-fill}
    stroke: ${math-stroke}
  }
}

20229: {
  label: "לינארית 2"
  style: {
    fill: ${math-fill}
    stroke: ${math-stroke}
  }
}

20425: {
  label: "הסתברות ומבוא לסטטיסטיקה למדמח"
  style: {
    fill: ${math-fill}
    stroke: ${math-stroke}
  }
}

# CS courses
20441: {
  label: "מבוא למדמח Java"
  style: {
    fill: ${cs-fill}
    stroke: ${cs-stroke}
  }
}

20407: {
  label: "מבני נתונים ומבוא לאלגוריתמים"
  style: {
    fill: ${cs-fill}
    stroke: ${cs-stroke}
  }
}

20465: {
  label: "מעבדה בתכנות מערכות"
  style: {
    fill: ${cs-fill}
    stroke: ${cs-stroke}
  }
}

20417: {
  label: "אלגוריתמים"
  style: {
    fill: ${cs-fill}
    stroke: ${cs-stroke}
  }
}

20604: {
  label: "מודלים חישוביים"
  style: {
    fill: ${cs-fill}
    stroke: ${cs-stroke}
  }
}

20466: {
  label: "לוגיקה למדעי המחשב"
  style: {
    fill: ${cs-fill}
    stroke: ${cs-stroke}
  }
}

20594: {
  label: "מערכות הפעלה"
  style: {
    fill: ${cs-fill}
    stroke: ${cs-stroke}
  }
}

20905: {
  label: "שפות תכנות"
  style: {
    fill: ${cs-fill}
    stroke: ${cs-stroke}
  }
}

20471: {
  label: "ארגון המחשב"
  style: {
    fill: ${cs-fill}
    stroke: ${cs-stroke}
  }
}

# prerequisites (regular), recommended (dash) 

20407 -> 20471: {
  style.stroke-dash: ${dash-style}
}
20465 -> 20471: {
  style.stroke-dash: ${dash-style}
}

20417 -> 20604: {
  style.stroke-dash: ${dash-style}
}

20466 -> 20604: {
  style.stroke-dash: ${dash-style}
}

20441 -> 20465
20441 -> 20407
20476 -> 20407
20407 -> 20604

20465 -> 20594

# 20905 שפות תכנות
20604 -> 20905
20417 -> 20905
20465 -> 20905

20476 -> 20466
20441 -> 20471
20474 -> 20475 -> 20425
20109 -> 20229
20407 -> 20594

# requirements of 20417
20407 -> 20417
# rec of 20417
20474 -> 20417: {
  style.stroke-dash: ${dash-style}
}
20109 -> 20417: {
  style.stroke-dash: ${dash-style}
}
20425 -> 20417: {
  style.stroke-dash: ${dash-style}
}
20364 -> 20905: {
  style.stroke-dash: ${dash-style}
}

20906 -> 20905: {
  style.stroke-dash: ${dash-style}
}

20441 -> 20277
20476 -> 20277
20407 -> 20277: {
  style.stroke-dash: ${dash-style}
}

20277: {
  label: "מערכות בסיסי נתונים"
  style: {
    fill: ${cs-fill-elective}
    stroke: ${cs-stroke-elective}
  }
}

20364: {
  label: "קומפילציה"
  style: {
    fill: ${cs-fill-elective}
    stroke: ${cs-stroke-elective}
  }
}

20906: {
  label: "תכנות מונחה עצמים"
  style: {
    fill: ${cs-fill-elective}
    stroke: ${cs-stroke-elective}
  }
}
